name: bstamp
version: '1.0.7'
summary: bstamp summary
description: |
             bstamp description

confinement: strict
base: core18
grade: stable
# icon: snap/gui/bstamp.png

# architectures:
#   - build-on: armhf
architectures:
  - build-on: amd64
system-usernames:
  snap_daemon: shared

slots:
  dbus-bstamp: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.bstamp # adjust accordingly to your app name and
    
apps:
  bstamp:
    command: bstamp
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the 
    # desktop: snap/gui/bstamp.desktop
    plugs:
    - network
    - desktop
    slots:
      - dbus-bstamp
parts:
  bstamp:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
